### ISSUE TITLE
Node version seems to be broken

### ISSUE THREAD

**Issue by squidfunk** [jpmorganchase/perspective#101]
I cannot get the Node examples to work, because I get the following error:

```
node_modules/@jpmorganchase/perspective/build/perspective.node.js:1850
module.exports = babel-runtime/helpers/typeof;
                                             ^

SyntaxError: Unexpected token ;
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

The compiled output looks broken, I assume the following exports should be strings?

![bildschirmfoto 2018-04-27 um 17 30 27](https://user-images.githubusercontent.com/932156/39371056-ded7179a-4a40-11e8-802b-0ffc16ba53c0.png)

Any ideas?

**Comment by texodus** [comment]
Thanks for the report - this is fixed on master and will be in 0.1.10

**Comment by squidfunk** [comment]
Any estimate on when 0.1.10 will be released?

**Comment by texodus** [comment]
1.1.10 is now released
