### ISSUE TITLE
"multiple single element removes" test fails intermittently under mysterious circumstances

### ISSUE THREAD

**Issue by texodus** [jpmorganchase/perspective#270]
Not always the same elements are not removed - but when the bug happens, it is reproducible and the same elements are un-removed in each iteration.

```javascript
perspective.js › WASM › Removes › multiple single element removes

    expect(received).toEqual(expected)

    Expected value to equal:
      [{"x": 0, "y": "test", "z": false}]
    Received:
      [{"x": 0, "y": "test", "z": false}, {"x": 148, "y": "test", "z": false}]

    Difference:

    - Expected
    + Received

    @@ -2,6 +2,11 @@
        Object {
          "x": 0,
          "y": "test",
          "z": false,
        },
    +   Object {
    +     "x": 148,
    +     "y": "test",
    +     "z": false,
    +   },
      ]
```

**Comment by sc1f** [comment]
Another failure this time with more elements unremoved:

```
  ● perspective.js › WASM › Removes › multiple single element removes

    expect(received).toEqual(expected)

    Expected value to equal:
      [{"x": 0, "y": "test", "z": false}]
    Received:
      [{"x": 123, "y": "test", "z": false}, {"x": 128, "y": "test", "z": false}, {"x": 159, "y": "test", "z": false}, {"x": 182, "y": "test", "z": false}]

    Difference:

    - Expected
    + Received

      Array [
        Object {
    -     "x": 0,
    +     "x": 123,
          "y": "test",
          "z": false,
        },
    +   Object {
    +     "x": 128,
    +     "y": "test",
    +     "z": false,
    +   },
    +   Object {
    +     "x": 159,
    +     "y": "test",
    +     "z": false,
    +   },
    +   Object {
    +     "x": 182,
    +     "y": "test",
    +     "z": false,
    +   },
      ]

      at Object._callee3$ (build/webpack:/test/js/updates.js:75:28)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
      at step (../../node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at ../../node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```
