### ISSUE TITLE
Issue in installing on Windows 10

### ISSUE THREAD

**Issue by Isaacsh** [jpmorganchase/perspective#90]
I tried to install `perspective-jupyterlab` 
```
jupyter labextension install @jpmorganchase/perspective-jupyterlab
```
and got the following error:
```
[1/4] Resolving packages...
warning @jpmorganchase/perspective-jupyterlab > @jpmorganchase/perspective-viewer-highcharts > highcharts-more@0.1.7: this package has been deprecated, just import modules from the highcharts folder
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 15:28:04.338 NotebookApp] > node C:\Users\FZBNBL\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
module.js:540
    throw err;
    ^

Error: Cannot find module '@jpmorganchase\perspective-jupyterlab\package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.resolve (internal/module.js:18:19)
    at C:\Users\FZBNBL\AppData\Local\Continuum\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:22:43
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (C:\Users\FZBNBL\AppData\Local\Continuum\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:21:22)
    at Object.<anonymous> (C:\Users\FZBNBL\AppData\Local\Continuum\Anaconda3\share\jupyter\lab\staging\webpack.config.js:19:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\FZBNBL\AppData\Local\Continuum\Anaconda3\share\jupyter\lab\staging\webpack.prod.config.js:5:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[W 15:32:22.989 NotebookApp] Build recommended
[W 15:32:22.989 NotebookApp] @jpmorganchase/perspective-jupyterlab needs to be included in build
```

![image](https://user-images.githubusercontent.com/7535009/38754581-6944b246-3f30-11e8-9109-950f6575c6c9.png)

Appreciate any words of wisdom anyone can spare.

**Comment by timkpaine** [comment]
I see the error `couldn't find the binary git`. Is git in your path?

`which git`
`where git`

**Comment by Isaacsh** [comment]
Yes believe so ...

```
C:\Users\FZBNBL>which git
C:\Program Files\Git\cmd\git.EXE

C:\Users\FZBNBL>where git
C:\Program Files\Git\cmd\git.exe
```

**Comment by timkpaine** [comment]
It doesn't look like this is an issue with perspective specifically: https://github.com/yarnpkg/yarn/issues/3102

**Comment by timkpaine** [comment]
Make sure it is in your path as well: https://stackoverflow.com/questions/49687848/fail-to-install-react-navigation-getting-git-not-available-error

**Comment by texodus** [comment]
Closing - feel free to open a new issue with additional detail, if you believe this to be an issue with Perspective itself.
